### ISSUE TITLE
wt watch errs on the second compile

### ISSUE THREAD

**Issue by rohanthewiz** [wellington/wellington#166] opened 2016-01-02 02:56 UTC
```bash
wt watch -proj sass -b css
File watcher started use `ctrl+d` to exit
```
The above compiles once, but on the next file modification:

```
2016/01/01 20:42:49 rebuild error: partial map lookup failed: /home/ro/go/src/github.com/rohanthewiz/susy1/sass/app.scss___jb_bak___
```

**Comment by drewwells** [comment] 2016-01-02 03:00
Duplicate of #165 

Switching around vendoring broke how dependencies are handled in go-libsass and this project, so packages look incompatible to the go compiler. I need to refactor some things. For now, I'd recommend installing 1.0.2 https://github.com/wellington/wellington/releases/tag/v1.0.2 but I should have this fixed in the next hour or so.

**Comment by rohanthewiz** [comment] 2016-01-02 03:03
Sorry I didn't see 165. Thanks man, just making it clear so the sake of others out there. Thanks again. It's great to get away from the heavy requirements of the Ruby system and have just a single exe for production compiles.

**Comment by drewwells** [comment] 2016-01-02 03:17
No problem! Thanks for testing wt out! Unfortunately, circleci wasn't affected by the submodule errors so I didn't catch this when I switched to submodules.

**Comment by drewwells** [comment] 2016-01-08 16:31
Is this working better for you now that spritewell is updated?

**Comment by rohanthewiz** [comment] 2016-01-12 05:20
Yes! Fixed.

**Closed** 2016-01-16 04:21 UTC
Labels: bug
